import { Issue, UserProfile, Comment, Notification } from "../types";

export const DEMO_USERS: UserProfile[] = [
  {
    id: "user_rajesh",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@gmail.com",
    photoURL: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
    points: 340,
    badges: ["first_step", "watchdog", "verified_voice"],
    issuesReported: 8,
    issuesResolved: 3,
    upvotesReceived: 55,
    joinedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "user_priya",
    name: "Priya Sharma",
    email: "priya.sharma@yahoo.com",
    photoURL: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
    points: 520,
    badges: ["first_step", "watchdog", "local_hero", "problem_solver", "elite_citizen"],
    issuesReported: 12,
    issuesResolved: 6,
    upvotesReceived: 95,
    joinedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "user_amit",
    name: "Amit Patil",
    email: "amit.patil@outlook.com",
    photoURL: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
    points: 120,
    badges: ["first_step", "verified_voice"],
    issuesReported: 3,
    issuesResolved: 1,
    upvotesReceived: 28,
    joinedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "user_sneha",
    name: "Sneha Jadhav",
    email: "sneha.jadhav@gmail.com",
    photoURL: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150",
    points: 80,
    badges: ["first_step"],
    issuesReported: 2,
    issuesResolved: 0,
    upvotesReceived: 12,
    joinedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "user_vikram",
    name: "Vikram Raje",
    email: "vikram.raje@gmail.com",
    photoURL: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150",
    points: 250,
    badges: ["first_step", "watchdog", "verified_voice"],
    issuesReported: 6,
    issuesResolved: 2,
    upvotesReceived: 38,
    joinedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const DEMO_ISSUES: Issue[] = [
  {
    id: "issue_pothole_1",
    title: "Dangerous Deep Crater Pothole",
    description: "A huge pothole has formed right in the middle of the street. It is highly dangerous for two-wheelers, especially at night and during rains. Multiple vehicles have already suffered minor accidents.",
    category: "Pothole",
    severity: "Critical",
    status: "In Progress",
    lat: 16.7025,
    lng: 74.2410,
    address: "Tarabai Road, near Mahalaxmi Temple, Kolhapur",
    ward: "Ward 4 - Mahalaxmi",
    city: "Kolhapur",
    imageURL: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=600",
    reportedBy: "user_rajesh",
    reporterName: "Rajesh Kumar",
    reporterPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
    upvotes: ["user_priya", "user_amit", "user_sneha", "user_vikram", "guest_1", "guest_2", "guest_3"],
    upvoteCount: 7,
    comments: 3,
    statusHistory: [
      { status: "Reported", timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(), note: "Issue logged in system." },
      { status: "Under Review", timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(), note: "Assigned to Ward Engineer for inspection." },
      { status: "In Progress", timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(), note: "Contractor assigned. Material procurement underway." }
    ],
    aiAnalysis: {
      category: "Pothole",
      severity: "Critical",
      confidence: 94,
      suggestedDept: "Public Works Department (PWD)",
      estimatedResolutionDays: 5,
      complaintLetter: "Subject: Urgent repair of deep crater pothole at Tarabai Road\n\nDear Ward Officer,\nI am writing to bring to your immediate attention a highly dangerous deep pothole on Tarabai Road, near Mahalaxmi Temple. It is about 1.5 feet deep and poses an imminent threat to life, particularly for motorcyclists. Please initiate emergency patch-up works immediately.\n\nSincerely,\nConcerned Citizen",
      resolutionSteps: "1. Area barricading & traffic diversion.\n2. Water removal and cavity excavation.\n3. Base compaction with crushed aggregate.\n4. Hot-mix asphalt filling and mechanical rolling."
    },
    isDuplicate: false,
    duplicateOf: null,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: null
  },
  {
    id: "issue_pothole_2",
    title: "Series of Potholes on Main Junction",
    description: "The main junction has developed massive potholes, turning the road completely unmotorable. It causes massive traffic jams during peak office hours and dust pollution.",
    category: "Pothole",
    severity: "High",
    status: "Reported",
    lat: 16.7115,
    lng: 74.2495,
    address: "Shivaji Road, near Rajarampuri Entrance, Kolhapur",
    ward: "Ward 12 - Rajarampuri",
    city: "Kolhapur",
    imageURL: "https://images.unsplash.com/photo-1599740831119-0725221349cb?w=600",
    reportedBy: "user_priya",
    reporterName: "Priya Sharma",
    reporterPhoto: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
    upvotes: ["user_rajesh", "user_amit", "user_sneha", "user_vikram", "guest_1", "guest_4", "guest_5", "guest_6", "guest_7", "guest_8"],
    upvoteCount: 10,
    comments: 1,
    statusHistory: [
      { status: "Reported", timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), note: "Issue reported by Priya Sharma. AI routing initiated." }
    ],
    aiAnalysis: {
      category: "Pothole",
      severity: "High",
      confidence: 88,
      suggestedDept: "Kolhapur Municipal Corporation (KMC)",
      estimatedResolutionDays: 7,
      complaintLetter: "Subject: Serious road deterioration at Shivaji Road Junction\n\nDear Municipal Commissioner,\nI would like to report severe road damage at the Rajarampuri Entrance junction. The entire road surface has peeled away, creating deep pockets that cause heavy traffic jams and damage vehicles. Kindly inspect and authorize reconstruction of this patch.\n\nRegards,\nPriya Sharma",
      resolutionSteps: "1. Clearing loose gravel and dirt.\n2. Sub-grade levelling.\n3. Laying bituminous base course.\n4. Overlaying final wear course."
    },
    isDuplicate: false,
    duplicateOf: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: null
  },
  {
    id: "issue_water_1",
    title: "Major Main Water Pipeline Leakage",
    description: "A huge underground drinking water pipeline has burst, wasting thousands of liters of clean water. The water is flooding the street and forming a massive muddy puddle, making it hard for pedestrians to cross.",
    category: "Water Leakage",
    severity: "High",
    status: "In Progress",
    lat: 16.6980,
    lng: 74.2340,
    address: "Mangalwar Peth Road, near Khasbag Maidan, Kolhapur",
    ward: "Ward 8 - Mangalwar Peth",
    city: "Kolhapur",
    imageURL: "https://images.unsplash.com/photo-1508873696983-2df519f0397e?w=600",
    reportedBy: "user_amit",
    reporterName: "Amit Patil",
    reporterPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
    upvotes: ["user_rajesh", "user_priya", "user_vikram", "guest_9", "guest_10", "guest_11"],
    upvoteCount: 6,
    comments: 2,
    statusHistory: [
      { status: "Reported", timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), note: "Water leakage reported." },
      { status: "Under Review", timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), note: "Water Supply department has received the alert." },
      { status: "In Progress", timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), note: "Excavation team is at the spot to locate and patch the main pipe." }
    ],
    aiAnalysis: {
      category: "Water Leakage",
      severity: "High",
      confidence: 96,
      suggestedDept: "Maharashtra Jeevan Pradhikaran (MJP)",
      estimatedResolutionDays: 3,
      complaintLetter: "Subject: Urgent: Potable water main pipe burst at Mangalwar Peth\n\nDear Executive Engineer,\nThis is to report a massive water pipe burst near Khasbag Maidan. Drinking water is spraying at high pressure, causing massive wastage and localized street flooding. Please close the main supply valve and repair immediately.\n\nWarm regards,\nAmit Patil",
      resolutionSteps: "1. Isolate pipeline section via control valves.\n2. Excavate road safely around the leak.\n3. Install a high-strength pipe clamp or replace the fractured segment.\n4. Sanitize and backfill the ditch."
    },
    isDuplicate: false,
    duplicateOf: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: null
  },
  {
    id: "issue_water_2",
    title: "Leaking Drinking Water Standpost",
    description: "The community standpost tap is broken, water has been continuously trickling for the past two weeks. The surrounding area has become highly slippery with moss growth.",
    category: "Water Leakage",
    severity: "Medium",
    status: "Resolved",
    lat: 16.7050,
    lng: 74.2510,
    address: "Shahupuri 3rd Lane, near Shahu Mill, Kolhapur",
    ward: "Ward 15 - Shahupuri",
    city: "Kolhapur",
    imageURL: "https://images.unsplash.com/photo-1542013936693-8848e5744a70?w=600",
    reportedBy: "user_vikram",
    reporterName: "Vikram Raje",
    reporterPhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150",
    upvotes: ["user_rajesh", "user_priya", "guest_12", "guest_13"],
    upvoteCount: 4,
    comments: 2,
    statusHistory: [
      { status: "Reported", timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), note: "Report logged." },
      { status: "Under Review", timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(), note: "Verified by Inspector." },
      { status: "In Progress", timestamp: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(), note: "Plumbing squad dispatched." },
      { status: "Resolved", timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(), note: "Replaced the valve and faucet unit. Cleaned moss around standpost." }
    ],
    aiAnalysis: {
      category: "Water Leakage",
      severity: "Medium",
      confidence: 91,
      suggestedDept: "KMC Water Works Department",
      estimatedResolutionDays: 4,
      complaintLetter: "Subject: Repair of leaking public tap standpost at Shahupuri\n\nDear Sir/Madam,\nI want to log a complaint about the broken faucet of the public drinking standpost in Shahupuri 3rd Lane. Moss has grown over the walking path, causing elderly residents to slip. Requesting a quick replacement of the tap nozzle.\n\nYours faithfully,\nVikram Raje",
      resolutionSteps: "1. Shut local distribution gate valve.\n2. Unscrew the damaged faucet.\n3. Fit a heavy-duty brass push tap.\n4. Clean the immediate drainage basin."
    },
    isDuplicate: false,
    duplicateOf: null,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "issue_light_1",
    title: "Broken Streetlight Near Girls Hostel",
    description: "The streetlight has been completely dead for over a week. The street becomes incredibly dark and sketchy at night, creating a major safety risk for female students walking back to the hostel.",
    category: "Streetlight",
    severity: "High",
    status: "Under Review",
    lat: 16.6890,
    lng: 74.2560,
    address: "Shivaji University Road, Vidyanagar, Kolhapur",
    ward: "Ward 22 - Vidyanagar",
    city: "Kolhapur",
    imageURL: "https://images.unsplash.com/photo-1509024644558-2f56ce76c490?w=600",
    reportedBy: "user_sneha",
    reporterName: "Sneha Jadhav",
    reporterPhoto: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150",
    upvotes: ["user_priya", "user_rajesh", "user_amit", "user_vikram", "guest_14", "guest_15", "guest_16", "guest_17"],
    upvoteCount: 8,
    comments: 4,
    statusHistory: [
      { status: "Reported", timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), note: "Reported by Sneha Jadhav. Priority raised due to proximity to Girls Hostel." },
      { status: "Under Review", timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), note: "Municipal electrical team has scheduled replacement." }
    ],
    aiAnalysis: {
      category: "Streetlight",
      severity: "High",
      confidence: 90,
      suggestedDept: "KMC Electrical Department",
      estimatedResolutionDays: 3,
      complaintLetter: "Subject: Safety Concern: Dark street due to non-functioning streetlight near Hostel\n\nDear Officer,\nI am writing to report that the streetlight opposite the main gate of the girls hostel at University Road is non-functional. It creates an extremely unsafe environment at night. Please replace the bulb/LED panel urgently.\n\nWarm regards,\nSneha Jadhav",
      resolutionSteps: "1. Inspection of wire connections at the pole base.\n2. Checking the photosensor/timer switch.\n3. Mounting bucket truck to replace the LED panel if burnt."
    },
    isDuplicate: false,
    duplicateOf: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: null
  },
  {
    id: "issue_light_2",
    title: "Blinking Flicker Streetlight",
    description: "The streetlight in front of Shahu Hospital has started flickering rapidly like a strobe light. It is causing major annoyance to patients in the wards and drivers passing by.",
    category: "Streetlight",
    severity: "Medium",
    status: "Resolved",
    lat: 16.6940,
    lng: 74.2440,
    address: "Dasara Chowk Road, Laxmipuri, Kolhapur",
    ward: "Ward 6 - Laxmipuri",
    city: "Kolhapur",
    imageURL: "https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?w=600",
    reportedBy: "user_rajesh",
    reporterName: "Rajesh Kumar",
    reporterPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
    upvotes: ["user_priya", "guest_18", "guest_19"],
    upvoteCount: 3,
    comments: 0,
    statusHistory: [
      { status: "Reported", timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), note: "Flickering reported." },
      { status: "Under Review", timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(), note: "Inspector confirmed driver unit failure." },
      { status: "In Progress", timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), note: "Repair truck dispatched." },
      { status: "Resolved", timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), note: "Replaced faulty LED driver and driver circuit box. Tested operational." }
    ],
    aiAnalysis: {
      category: "Streetlight",
      severity: "Medium",
      confidence: 85,
      suggestedDept: "Electrical Engineering Wing, KMC",
      estimatedResolutionDays: 4,
      complaintLetter: "Subject: Blinking streetlight nuisance in front of Shahu Hospital\n\nDear Electrical Inspector,\nThere is a flickering streetlight right in front of Shahu Hospital, Laxmipuri. The strobe effect is highly disruptive for the recuperating patients in ICU and wards, and is blinding drivers. Kindly fix the choke/driver.\n\nSincerely,\nRajesh Kumar",
      resolutionSteps: "1. Access junction box on light pole.\n2. Disconnect and remove damaged LED driver.\n3. Install new solid-state constant-current driver.\n4. Check insulation resistance."
    },
    isDuplicate: false,
    duplicateOf: null,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "issue_waste_1",
    title: "Overflowing Garbage Bin & Wild Animals",
    description: "The secondary municipal garbage bin has not been cleared for 4 days. Waste is overflowing onto the main sidewalk. Stray cattle and dogs are pulling plastic bags around, creating a terrible stench and hygiene threat.",
    category: "Waste",
    severity: "High",
    status: "Reported",
    lat: 16.7150,
    lng: 74.2280,
    address: "Rankala Lake Circular Road, Kolhapur",
    ward: "Ward 2 - Rankala",
    city: "Kolhapur",
    imageURL: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600",
    reportedBy: "user_priya",
    reporterName: "Priya Sharma",
    reporterPhoto: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
    upvotes: ["user_rajesh", "user_amit", "user_sneha", "user_vikram", "guest_20", "guest_21", "guest_22", "guest_23", "guest_24"],
    upvoteCount: 9,
    comments: 2,
    statusHistory: [
      { status: "Reported", timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), note: "Report logged. Notified Rankala Solid Waste Management team." }
    ],
    aiAnalysis: {
      category: "Waste",
      severity: "High",
      confidence: 93,
      suggestedDept: "KMC Solid Waste Management (SWM)",
      estimatedResolutionDays: 2,
      complaintLetter: "Subject: Unattended municipal garbage overflow at Rankala Lake Road\n\nDear Health Officer,\nThis is to report that the central garbage dumper on Rankala Circular Road is overflowing heavily. It has not been picked up this week. Stray animals are scattering the trash, making it a health hazard for tourists visiting Rankala Lake. Please order immediate clearance.\n\nThank you,\nPriya Sharma",
      resolutionSteps: "1. Dispatching a compactor truck to lift the bin.\n2. Manual sweeping of spilled plastic and debris.\n3. Disinfecting the ground area with bleaching powder.\n4. Resetting the empty container."
    },
    isDuplicate: false,
    duplicateOf: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: null
  },
  {
    id: "issue_waste_2",
    title: "Illegal E-Waste & Plastic Dumping Site",
    description: "Some commercial operators are dumping cardboard packages, bubble wrap, and scrap electronics in the open plot behind the residential area during the night. Highly toxic and fire hazard.",
    category: "Waste",
    severity: "High",
    status: "Resolved",
    lat: 16.7210,
    lng: 74.2620,
    address: "Udyam Nagar Industrial Area, Kolhapur",
    ward: "Ward 19 - Udyam Nagar",
    city: "Kolhapur",
    imageURL: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=600",
    reportedBy: "user_vikram",
    reporterName: "Vikram Raje",
    reporterPhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150",
    upvotes: ["user_priya", "user_rajesh", "guest_25", "guest_26", "guest_27"],
    upvoteCount: 5,
    comments: 1,
    statusHistory: [
      { status: "Reported", timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(), note: "Illegal dumping reported." },
      { status: "Under Review", timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(), note: "Environmental inspectors visited. Issued notices to adjacent warehouses." },
      { status: "In Progress", timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(), note: "Trucks cleared the electronic components." },
      { status: "Resolved", timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), note: "Completely cleared. Installed 'No Dumping - Fine 5000 INR' warnings board and closed entry chain." }
    ],
    aiAnalysis: {
      category: "Waste",
      severity: "High",
      confidence: 89,
      suggestedDept: "Maharashtra Pollution Control Board (MPCB)",
      estimatedResolutionDays: 6,
      complaintLetter: "Subject: Illegal hazardous commercial e-waste dumping in Udyam Nagar\n\nDear Regional Officer,\nThis is to report hazardous plastic, wire cladding, and battery scrap dumping in the residential buffers of Udyam Nagar. This illegal dumping happens at night. Please inspect, clean, and fine the culprits.\n\nSincerely,\nVikram Raje",
      resolutionSteps: "1. Cordon off the chemical/e-waste plot.\n2. Segregate recyclable plastics and lead/electronics scrap.\n3. Safe transport to authorized e-waste disposal center.\n4. Install CCTV surveillance or caution boards."
    },
    isDuplicate: false,
    duplicateOf: null,
    createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "issue_encroachment_1",
    title: "Vegetable Stalls Encroaching Footpath",
    description: "Stalls have completely setup shade tarps, tables, and wooden boxes on the pedestrian walkway. Pedestrians, including young kids, are forced to walk on the busy main road with fast-moving traffic, creating potential safety issues.",
    category: "Encroachment",
    severity: "Medium",
    status: "Under Review",
    lat: 16.7080,
    lng: 74.2390,
    address: "Rajarampuri Main Road, near 2nd Lane, Kolhapur",
    ward: "Ward 11 - Rajarampuri",
    city: "Kolhapur",
    imageURL: "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=600",
    reportedBy: "user_rajesh",
    reporterName: "Rajesh Kumar",
    reporterPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
    upvotes: ["user_priya", "user_amit", "guest_28", "guest_29"],
    upvoteCount: 4,
    comments: 1,
    statusHistory: [
      { status: "Reported", timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), note: "Reported." },
      { status: "Under Review", timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), note: "KMC Encroachment squad notified for warning issuance." }
    ],
    aiAnalysis: {
      category: "Encroachment",
      severity: "Medium",
      confidence: 82,
      suggestedDept: "KMC Anti-Encroachment Department",
      estimatedResolutionDays: 5,
      complaintLetter: "Subject: Request to clear footway encroachment at Rajarampuri Main Road\n\nDear Commissioner,\nI would like to report severe encroachment of the footpath near 2nd Lane in Rajarampuri by commercial vendors. While we support local vendors, blocking footpaths puts citizens' lives at risk on this busy road. Kindly relocate them to the weekly market yard.\n\nSincerely,\nRajesh Kumar",
      resolutionSteps: "1. Inspection and photographic survey of encroached footpath.\n2. Issue 48-hour voluntary clearance notice to vendors.\n3. Execute joint evacuation drive if compliance is not met.\n4. Designate dedicated yellow lines for legal vending zones."
    },
    isDuplicate: false,
    duplicateOf: null,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: null
  },
  {
    id: "issue_drainage_1",
    title: "Overflowing Open Drainage Gutter",
    description: "The main drainage conduit has blocked, resulting in dark black sludge sewage overflowing on the street. It has caused a severe toxic stench, swarms of mosquitoes, and people cannot step out of their homes.",
    category: "Other", // Will treat as drainage / other
    severity: "Critical",
    status: "In Progress",
    lat: 16.6970,
    lng: 74.2250,
    address: "Pratikhya Colony, near Juna Budhwar Peth, Kolhapur",
    ward: "Ward 9 - Budhwar Peth",
    city: "Kolhapur",
    imageURL: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600",
    reportedBy: "user_priya",
    reporterName: "Priya Sharma",
    reporterPhoto: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
    upvotes: ["user_rajesh", "user_sneha", "user_vikram", "user_amit", "guest_30", "guest_31", "guest_32", "guest_33", "guest_34", "guest_35"],
    upvoteCount: 10,
    comments: 5,
    statusHistory: [
      { status: "Reported", timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), note: "Urgent drainage overflow logged." },
      { status: "Under Review", timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), note: "KMC Sanitation officer inspected. Heavy clogging found due to plastic bags." },
      { status: "In Progress", timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), note: "Sewer jetting machine and crew deployed." }
    ],
    aiAnalysis: {
      category: "Other",
      severity: "Critical",
      confidence: 95,
      suggestedDept: "Sewerage & Sanitation Board, KMC",
      estimatedResolutionDays: 2,
      complaintLetter: "Subject: Extreme health emergency: Sewer overflow at Budhwar Peth\n\nDear Health Superintendent,\nI am writing to log an emergency complaint regarding overflowing black sewage sludge on Pratikhya Colony street. The entire street is flooded with toxic, highly smelly water. Mosquito breeding has exploded. Please deploy the high-pressure jetting machine immediately.\n\nWith concern,\nPriya Sharma",
      resolutionSteps: "1. Deploy high-vacuum sewer suction trucks.\n2. Manual desilting of the chamber opening to remove plastic blocking.\n3. Jet wash conduits to ensure free flow.\n4. Bleaching powder and chemical misting for vector control."
    },
    isDuplicate: false,
    duplicateOf: null,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: null
  }
];

export const DEMO_COMMENTS: Comment[] = [
  {
    id: "comment_1",
    issueId: "issue_pothole_1",
    userId: "user_priya",
    userName: "Priya Sharma",
    userPhoto: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
    text: "I passed by this place yesterday. It is incredibly deep, nearly broke my scooter's suspension. Please drive very carefully here!",
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comment_2",
    issueId: "issue_pothole_1",
    userId: "user_vikram",
    userName: "Vikram Raje",
    userPhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150",
    text: "The local corporator was informed directly, good to see it is now marked 'In Progress' here. Hope they lay the gravel soon.",
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comment_3",
    issueId: "issue_pothole_1",
    userId: "user_rajesh",
    userName: "Rajesh Kumar",
    userPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
    text: "Thanks Priya and Vikram for verifying. I'll keep pushing updates on this card as I see progress.",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comment_4",
    issueId: "issue_light_1",
    userId: "user_priya",
    userName: "Priya Sharma",
    userPhoto: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
    text: "Yes, this is an absolute security concern. The whole lane becomes pitch black. Upvoted for high priority!",
    createdAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comment_5",
    issueId: "issue_drainage_1",
    userId: "user_amit",
    userName: "Amit Patil",
    userPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
    text: "The smell has entered our kitchens! Kids cannot play outside. Please clean this immediately, KMC!!",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  }
];
